
export const LIST_MOVIE_LOADING = 'LIST_MOVIE_LOADING';
export const LIST_MOVIE_SUCCESS = 'LIST_MOVIE_SUCCESS';
export const LIST_MOVIE_ERROR = 'LIST_MOVIE_ERROR';
export const LIST_INITIAL_MOVIE = 'LIST_INITIAL_MOVIE';
export const LIST_INITIAL_MOVIE_ERROR = 'LIST_INITIAL_MOVIE_ERROR';
export const DETAIL_MOVIE_LOADING = 'DETAIL_MOVIE_LOADING';
export const DETAIL_MOVIE_SUCCESS = 'DETAIL_MOVIE_SUCCESS';
export const DETAIL_MOVIE_ERROR = 'DETAIL_MOVIE_ERROR';
